import json

def export_to_python(macro_data, filename):
    """Convert PyMacroRecord JSON to executable Python script"""
    
    python_code = """#!/usr/bin/env python3
# Generated by PyMacroRecord
import pyautogui
import time
from pynput.keyboard import Key

# Disable pyautogui failsafe (move mouse to corner to abort)
pyautogui.FAILSAFE = False

def play_macro():
"""
    
    # Extract settings if present
    if "settings" in macro_data:
        settings = macro_data["settings"]
        repeat_times = settings["Playback"]["Repeat"]["Times"]
        speed = settings["Playback"]["Speed"]
    else:
        repeat_times = 1
        speed = 1.0
    
    # Generate main loop
    python_code += f"    # Repeat {repeat_times} times\n"
    python_code += f"    for i in range({repeat_times}):\n"
    python_code += f"        print(f'Playing iteration {{i+1}}/{repeat_times}')\n"
    
    for i, event in enumerate(macro_data["events"]):
        timestamp = event["timestamp"] / speed
        
        # Add sleep for timing (skip first event)
        if i > 0 and timestamp > 0:
            python_code += f"        time.sleep({timestamp:.3f})\n"
        
        # Convert each event type
        if event["type"] == "cursorMove":
            python_code += f"        pyautogui.moveTo({event['x']}, {event['y']})\n"
            
        elif event["type"] == "scrollEvent":
            python_code += f"        pyautogui.scroll({event['dy']}, x=pyautogui.position()[0], y=pyautogui.position()[1])\n"
            
        elif event["type"] in ["leftClickEvent", "rightClickEvent", "middleClickEvent"]:
            button = event["type"].replace("ClickEvent", "")
            if event["pressed"]:
                python_code += f"        pyautogui.mouseDown(x={event['x']}, y={event['y']}, button='{button}')\n"
            else:
                python_code += f"        pyautogui.mouseUp(x={event['x']}, y={event['y']}, button='{button}')\n"
                
        elif event["type"] == "keyboardEvent":
            key = event["key"]
            # Clean up the key representation
            if key.startswith("Key."):
                # Special keys (shift, ctrl, etc)
                key_name = key.replace("Key.", "").replace("_l", "").replace("_r", "")
                action = "Down" if event["pressed"] else "Up"
                python_code += f"        pyautogui.key{action}('{key_name}')\n"
            elif key.startswith("'") and key.endswith("'"):
                # Regular character key
                char = key[1:-1]
                action = "Down" if event["pressed"] else "Up"
                python_code += f"        pyautogui.key{action}('{char}')\n"
            elif key.startswith("<") and key.endswith(">"):
                # Virtual key codes - skip for now
                python_code += f"        # Skipped virtual key: {key}\n"
            else:
                # Direct key
                action = "Down" if event["pressed"] else "Up"
                python_code += f"        pyautogui.key{action}('{key}')\n"
    
    # Add footer
    python_code += """
if __name__ == '__main__':
    print("Starting macro playback in 3 seconds...")
    time.sleep(3)
    play_macro()
    print("Macro playback complete!")
"""
    
    with open(filename, 'w') as f:
        f.write(python_code)

# Test data
test_data = {
    "settings": {"Playback": {"Speed": 1, "Repeat": {"Times": 1}}},
    "events": [
        {"type": "cursorMove", "x": 100, "y": 200, "timestamp": 0.5},
        {"type": "leftClickEvent", "x": 100, "y": 200, "pressed": True, "timestamp": 0.1}
    ]
}

export_to_python(test_data, "test_output.py")
print("Created test_output.py!")
