#!/usr/bin/env python3
# Generated by PyMacroRecord
import pyautogui
import time
from pynput.keyboard import Key

# Disable pyautogui failsafe (move mouse to corner to abort)
pyautogui.FAILSAFE = False

def play_macro():
    # Repeat 1 times
    for i in range(1):
        print(f'Playing iteration {i+1}/1')
        pyautogui.moveTo(100, 200)
        time.sleep(0.100)
        pyautogui.mouseDown(x=100, y=200, button='left')

if __name__ == '__main__':
    print("Starting macro playback in 3 seconds...")
    time.sleep(3)
    play_macro()
    print("Macro playback complete!")
